version: "3.7"
services:
  nestjs:
    image: zeepje/whoiswhere:latest
    build: .
    ports:
      - "1337:3000"
  whoiswhere-mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: whoiswhere
