version: "3.7"
services:
  whoiswhere-postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      # POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: whoiswhere
      POSTGRES_USER: postgres
    volumes:
      - whoiswhere-datavolume:/var/lib/POSTGRES
  nestjs:
    image: zeepje/whoiswhere:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - whoiswhere-postgresql
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: yarn start:dev
volumes:
  whoiswhere-datavolume:
