version: "3.7"
services:
  whoiswhere-mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: whoiswhere
    volumes:
      - whoiswhere-datavolume:/var/lib/mysql
  nestjs:
    image: zeepje/whoiswhere:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - whoiswhere-mysql
volumes:
  whoiswhere-datavolume:
